### ISSUE TITLE
Is it possible to use it together with web-mode?

### ISSUE THREAD

**Issue by proofit404** [emacs-lsp/lsp-html#1]

**Comment by vibhavp** [comment]
Should be. However, `web-mode` is also invoked for certain non-HTML files as well, so you would need a setup similar to the one detailed in [lsp-css](https://github.com/emacs-lsp/lsp-css) (`my-css-mode-setup`) to make sure lsp-html is only invoked for `.html` files.

**Comment by proofit404** [comment]
Thanks for explaining! Will report if something goes wrong.
